name: talker
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.0 <3.0.0'


dependencies:
  talker_error_handler:
    path:
      ../talker_error_handler

dev_dependencies:
  lint: ^1.8.1
  test: ^1.16.0
