name: talker_error_handler
description: Error handler core package for talker (advanced error handler and logger package)
version: 0.2.1
homepage: https://github.com/Frezyx/talker

environment:
  sdk: '>=2.15.0 <3.0.0'


dependencies:
#   path: ^1.8.0

dev_dependencies:
  lint: ^1.8.1
  test: ^1.16.0
  
