name: talker
description: Advanced error handler and logger package for flutter and dart. App monitoring, logs history, report sharing, custom logs, and etc.
version: 3.0.3
homepage: https://github.com/Frezyx/talker
repository: https://github.com/Frezyx/talker
issue_tracker: https://github.com/Frezyx/talker/issues

environment:
  sdk: '>=2.15.0 <4.0.0'

dependencies:
  talker_logger: ^3.0.4

dev_dependencies:
  dart_code_metrics: ^5.7.4
  lint: ^2.0.1
  test: ^1.22.1
