name: talker
description: Advanced error handler and logger package for flutter and dart apps
version: 1.3.0
homepage: https://github.com/Frezyx/talker

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  talker_logger: 1.2.1
    # path:
    #   ../talker_logger
    # git:
    #   url: https://github.com/Frezyx/talker
    #   ref: testing
    #   path: talker_logger/

dev_dependencies:
  lint: ^1.8.1
  test: ^1.16.0
