name: talker
description: Advanced and simple error handler and logger for dart and flutter apps with history, sharing, customization, etc.
version: 2.2.0-dev.1
homepage: https://github.com/Frezyx/talker
repository: https://github.com/Frezyx/talker
issue_tracker: https://github.com/Frezyx/talker/issues

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  talker_logger: ^2.2.0-dev.1
    # path:
    #   ../talker_logger
    # git:
    #   url: https://github.com/Frezyx/talker
    #   ref: testing
    #   path: talker_logger/

dev_dependencies:
  lint: ^1.8.1
  test: ^1.16.0
