name: talker_dio_logger
description: Lightweight and customizable dio http client logger on talker base
version: 2.0.0-dev.1
homepage: https://github.com/Frezyx/talker

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  dio: ^5.0.0
  talker: ^3.0.0-dev.4
    # path:
    #   ../talker

dev_dependencies:
  lint: ^2.0.1
  test: ^1.23.1
