name: talker_shop_app_example
description: Talker flutter example shop application
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  talker_flutter: #^0.12.0
    path:
      ../../packages/talker_flutter
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
