name: talker_logger
description: Logger. Easy, customizable, extensible logging, lightweight with filters, formatters, custom logs, log levels.
version: 3.0.3
homepage: https://github.com/Frezyx/talker
repository: https://github.com/Frezyx/talker
issue_tracker: https://github.com/Frezyx/talker/issues

environment:
  sdk: '>=2.15.0 <4.0.0'

dependencies:
  ansicolor: ^2.0.1

dev_dependencies:
  lint: ^2.0.1
  test: ^1.22.1
