name: talker_logger
description: Logger core package for talker (advanced error handler and logger package)
version: 0.8.0
homepage: https://github.com/Frezyx/talker

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  ansicolor: ^2.0.1

dev_dependencies:
  lint: ^1.8.1
  test: ^1.16.0
