name: talker_flutter

on:
  push:
    paths:
      - "packages/talker_flutter/**"
      - ".github/workflows/talker_flutter.yaml"
  pull_request:
    paths:
      - "packages/talker_flutter/**"
      - ".github/workflows/talker_flutter.yaml"
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github
permissions: read-all

jobs:
  analyze:
    defaults:
      run:
        working-directory: packages/talker_flutter
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - name: Disable Flutter analytics
        continue-on-error: true
        run: |
          set -e
          FLUTTER_SDK_VERSION=$(flutter --version --machine | yq e -r '.frameworkVersion' -)
          FLUTTER_SDK_VERSION_MAJOR="${FLUTTER_SDK_VERSION%%\.*}"
          FLUTTER_SDK_VERSION_MINOR="${FLUTTER_SDK_VERSION#*.}"
          FLUTTER_SDK_VERSION_MINOR="${FLUTTER_SDK_VERSION_MINOR%.*}"
          FLUTTER_SDK_VERSION_PATCH="${FLUTTER_SDK_VERSION##*.}"
          if [[ "$FLUTTER_SDK_VERSION_MAJOR" -gt 3 || ( "$FLUTTER_SDK_VERSION_MAJOR" -eq 3 && "$FLUTTER_SDK_VERSION_MINOR" -gt 15 ) ]]; then
            flutter config --no-analytics
          else
            flutter --disable-telemetry
          fi
      - name: Install Dependencies
        run: flutter pub get --no-example
      - name: Format
        run: dart format lib --set-exit-if-changed
      - name: Analyze
        run: flutter analyze lib --fatal-warnings
