name: talker_logger

on:
  push:
    paths:
      - "packages/talker_logger/**"
      - ".github/workflows/talker_logger.yaml"

  pull_request:
    paths:
      - "packages/talker_logger/**"
      - ".github/workflows/talker_logger.yaml"

jobs:
  build:
    defaults:
      run:
        working-directory: packages/talker_logger

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - name: Install Dependencies
        run: dart pub get

      - name: Format
        run: dart format --set-exit-if-changed .

      - name: Analyze
        run: dart analyze --fatal-infos --fatal-warnings .

      - name: Run Tests
        # run: |
        #   pub global activate test_coverage
        #   export PATH=$PATH:$HOME/.pub-cache/bin
        #   test_coverage
        run: flutter test --coverage
      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.2.0
        with:
          path: packages/talker_logger/coverage/lcov.info
          min_coverage: 60

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      # - name: Run Tests
      #   run: |
      #     pub global activate test_coverage
      #     export PATH=$PATH:$HOME/.pub-cache/bin
      #     test_coverage
      # - name: Check Code Coverage
      #   uses: VeryGoodOpenSource/very_good_coverage@v1.2.0
      #   with:
      #     min_coverage: 30
      #     path: talker_logger/coverage/lcov.info
