name: talker_dio_logger

on:
  push:
    paths:
      - "packages/talker_dio_logger/**"
      - ".github/workflows/talker_dio_logger.yaml"
  pull_request:
    paths:
      - "packages/talker_dio_logger/**"
      - ".github/workflows/talker_dio_logger.yaml"
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github
permissions: read-all

jobs:
  test:
    uses: ./.github/workflows/dart_test.yaml
    with:
      package: talker_dio_logger
