name: talker_flutter

on:
  push:
    paths:
      - "packages/talker_flutter/**"
      - ".github/workflows/talker_flutter.yaml"
  pull_request:
    paths:
      - "packages/talker_flutter/**"
      - ".github/workflows/talker_flutter.yaml"
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github
permissions: read-all

jobs:
  build:
    defaults:
      run:
        working-directory: packages/talker_flutter
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - name: Install Dependencies
        run: flutter pub get --no-example
      - name: Format
        run: dart format lib --set-exit-if-changed
      - name: Analyze
        run: flutter analyze lib --fatal-warnings
