name: talker_logger

on:
  push:
    paths:
      - "packages/talker_logger/**"
      - ".github/workflows/talker_logger.yaml"
  pull_request:
    paths:
      - "packages/talker_logger/**"
      - ".github/workflows/talker_logger.yaml"
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github
permissions: read-all

jobs:
  test:
    uses: ./.github/workflows/test.yaml
    with:
      package: talker_logger
      sdk: dart
