name: talker_bloc_logger

on:
  push:
    paths:
      - "packages/talker_bloc_logger/**"
      - ".github/workflows/talker_bloc_logger.yaml"

  pull_request:
    paths:
      - "packages/talker_bloc_logger/**"
      - ".github/workflows/talker_bloc_logger.yaml"

jobs:
  test:
    uses: ./.github/workflows/dart_test.yaml
    with:
      package: talker_bloc_logger
