name: talker_error_hanlder

on:
  push:
    paths:
      - "talker_error_hanlder/**"
      - ".github/workflows/talker_error_hanlder.yaml"

  pull_request:
    paths:
      - "talker_error_hanlder/**"
      - ".github/workflows/talker_error_hanlder.yaml"

jobs:
  build:
    defaults:
      run:
        working-directory: talker_error_hanlder

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - name: Install Dependencies
        run: dart pub get

      - name: Format
        run: dart format --set-exit-if-changed .

      - name: Analyze
        run: dart analyze --fatal-infos --fatal-warnings .

      - name: Run Tests
        run: |
          pub global activate test_coverage
          export PATH=$PATH:$HOME/.pub-cache/bin
          test_coverage
      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.2.0
        with:
          min_coverage: 30
          path: talker_error_hanlder/coverage/lcov.info
