name: talker_bloc_logger
description: Lightweight and customizable BLoC state management library logger on talker base.
version: 2.0.0-dev.1
homepage: https://github.com/Frezyx/talker
repository: https://github.com/Frezyx/talker
issue_tracker: https://github.com/Frezyx/talker/issues

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  talker: ^3.0.0-dev.4
    # path:
    #   ../talker
  bloc: ^8.1.1
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
