name: talker_bloc_logger
description: Lightweight and customizable BLoC state management library logger on talker base.
version: 0.1.1
homepage: https://github.com/Frezyx/talker
repository: https://github.com/Frezyx/talker
issue_tracker: https://github.com/Frezyx/talker/issues

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  talker: ^2.4.0
  bloc: ^8.1.0
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
