name: talker_flutter
description: Flutter extensions for talker. Advanced and simple error handler and logger for dart and flutter apps with history, sharing, customization, etc.
version: 3.0.0-dev.7
homepage: https://github.com/Frezyx/talker
repository: https://github.com/Frezyx/talker
issue_tracker: https://github.com/Frezyx/talker/issues

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

  talker: ^3.0.0-dev.8
    # path:
    #   ../../packages/talker
  # talker_dio_logger: #^1.3.0
  #   path:
  #     ../../packages/talker_dio_logger
    # path:
    #   ../../packages/talker_dio_logger
  group_button: ^5.3.0
  path_provider: ^2.0.15
  share_plus: ^7.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
