name: talker_flutter
description: Flutter implementation of talker (advanced error handler and logger package).
version: 2.0.4
homepage: https://github.com/Frezyx/talker

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

  talker: ^2.0.0
  group_button: ^5.2.2
  path_provider: ^2.0.11
  share_plus: ">=4.5.3 <5.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
